### ISSUE TITLE
graph displays 'show all' on update

### ISSUE THREAD

**Issue by hombrew** [amcharts/amcharts3-react#22]
I don't know if this is configurable, but everytime 'dataProvider' is updated, the graph displays a button that says 'show all'. I'd like it to display the new data inmediatly.

this is how the chart data is being generated:
```javascript
this.GRAPH_DATA = {
   ...
   'dataProvider': this.props.data.previous,
   ...
}
```
and this is how it is displayed

```javascript
<AmCharts {...this.GRAPH_DATA}/>
```

`this.props.data` is updated via an api that is being fetched after a button is clicked by the parent component.

Thanks in advance for any help you can offer.

**Comment by Pauan** [comment]
@hombrew Every time you call the `this.setState` method it will update the chart. Are you calling `setState` immediately after setting the new data?

**Comment by bleachdugu** [comment]
same problem occurs in my project.  I use some dirty tricky way to solve it. 
the data provider in my project was stored in my reduce state, once it update, the chart will rerendered and display showall,  then I added a listener to the chart, once it rerendered and call the function to force the chart show all 
```
(event) => {
event.chart.zoomOut();
}
```

it solve my problem ,but its a dirty way I though haha

**Comment by Pauan** [comment]
@hombrew @bleachdugu I was able to reproduce this bug, and I fixed it.

Please upgrade `amcharts3-react` to version `1.1.7`

You can upgrade by deleting `node_modules/amcharts3-react` and then running `npm install`

**Comment by hombrew** [comment]
thank you very much!!

**Comment by devilsbibble** [comment]
Could someone help me about this problem? 
My `amcharts3-react` version is `3.21.5` , but still have this problem

**Comment by Pauan** [comment]
@devilsbibble It seems this got broken again.

We just now released a fix in [version `3.21.6` of AmCharts](https://www.amcharts.com/download/).

If you are using our CDN (`https://www.amcharts.com/lib/3/amcharts.js`) then you do not need to change anything, you already have the fix. You might need to clear your browser's cache.

If you downloaded AmCharts from somewhere else (such as our Commercial Downloads center, or npm) then you will need to redownload the latest version of AmCharts.

[Here is a working demo.](https://codepen.io/team/amcharts/pen/01f297ea6e07c6555dfe8f20e9fa46bf)
